// src/app/api/generate-site/route.ts
import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';
import { generateSiteStream } from './generateSiteStream';
import ContentSafetyLayer from '@/validation/ContentSafetyLayer';
import { enforceCredits, refundReservation } from '@/billing/middleware';
import { getRedisClient } from '@/lib/redis-health';
import { createRateLimiter } from '@/lib/rate-limiter';
import { logger } from '@/lib/logger';

// SSE helper
function sseHeaders() {
  return {
    'Content-Type': 'text/event-stream',
    'Cache-Control': 'no-cache, no-transform',
    Connection: 'keep-alive',
  };
}

// generateSiteStream is provided from './generateSiteStream' so it can be tested

export async function POST(req: NextRequest) {
  const body = await req.json().catch(() => ({}));
  const description = body.description || 'Website generated by AI';
  const preferences = body.preferences || { designStyle: 'modern', contentTone: 'neutral', performancePriority: 'high' };
  const userId = body.userId || 'anonymous';

  // Rate limiting: check user hasn't exceeded request quota
  const redis = getRedisClient();
  if (redis) {
    const limiter = createRateLimiter(redis, { windowMs: 60000, maxRequests: 10 });
    const { allowed, remaining } = await limiter.check(userId);
    if (!allowed) {
      logger.warn({ userId, remaining }, 'Rate limit exceeded');
      return NextResponse.json(
        { error: 'rate_limit_exceeded', remaining },
        { status: 429, headers: { 'Retry-After': '60' } }
      );
    }
  }

  // Credits enforcement — estimate 10 units
  const creditCheck = await enforceCredits(req, userId, 10);
  if (!creditCheck.ok) {
    logger.warn({ userId, credits: creditCheck.credits }, 'Insufficient credits');
    return NextResponse.json({ error: 'insufficient_credits', credits: creditCheck.credits ?? 0 }, { status: 402 });
  }

  const responseStream = await generateSiteStream({ description, preferences, userId, reserved: creditCheck.reserved, credits: creditCheck.credits });
  return new NextResponse(responseStream, { headers: sseHeaders() });
}

export const runtime = 'nodejs';
